### PR TITLE
Update Dockerfile

### PR DESCRIPTION
**Pull request by erigo**
Add MinIO Client for migrating data in each Milvus cluster.

### CODE REVIEW

**Comment by wayblink** [comment]
@erigo Hi, Thanks for contribution. Why we need that?

**Comment by wayblink** [comment]
@erigo I get your point, good for now. We will support cross storage backup in our roadmap. Then you will not need to use mc client to copy to local. How about the image size change after you add mc client.

**Comment by erigo** [comment]
image size from 41.7MB to 68.2MB.

**Comment by wayblink** [comment]
@erigo Merged.

**Pull request merged**
